# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty-prompt"

gem "tty-progressbar", "~> 0.18.2"

gem 'io-console'

gem "httparty", "~> 0.18.1" 